-- ============================================================
-- 02_facts.sql
-- Creates fact table view for the NHL shot analysis project.
-- ============================================================
-- fact_shot_events

CREATE OR REPLACE VIEW fact_shot_events AS
SELECT
    season::int AS season,
    game_id::int AS game_id,
    shot_id::int AS shot_id,
    shooter_player_id::int AS shooter_player_id,
    goalie_id_for_shot::int AS goalie_id_for_shot,
    team_code,
    shot_type,
    period ::int AS period,
	time,
	is_playoff_game,
	is_home_team,
	home_team_code,
	away_team_code,
	home_team_goals,
	away_team_goals,
	event,
	goal,
	shot_was_on_goal,
	shot_distance,
	shot_angle,
	shot_angle_adjusted,
	arena_adjusted_shot_distance,
	shot_rebound,
	shot_rush,
	off_wing,
	shot_on_empty_net,
	shot_angle_plus_rebound,
	shot_angle_plus_rebound_speed,
	shot_angle_rebound_royal_road,
	arena_adjusted_xcord,
	arena_adjusted_ycord,
	arena_adjusted_xcord_abs,
	arena_adjusted_ycord_abs,
	x_goal,
	x_rebound,
	x_froze,
	x_play_continued_in_zone,
	x_play_continued_outside_zone,
	x_play_stopped,
	x_shot_was_on_goal,
	last_event_category,
	distance_from_last_event,
	speed_from_last_event,
	time_since_last_event,
	time_until_next_event,
	time_since_faceoff,
	player_position_that_did_event,
	player_num_that_did_event,
	player_num_that_did_last_event,
	home_skaters_on_ice,
	away_skaters_on_ice,
	shooting_team_forwards_on_ice,
	shooting_team_defencemen_on_ice,
	defending_team_forwards_on_ice,
	defending_team_defencemen_on_ice,
	away_penalty1_time_left,
	home_penalty1_time_left,
	away_penalty1_length,
	home_penalty1_length,
	shooter_time_on_ice,
	shooting_team_average_time_on_ice,
	shooting_team_max_time_on_ice,
	shooting_team_min_time_on_ice,
	time_difference_since_change,
	average_rest_difference
FROM shots_2007_2025;

-- fact_team_game_performance

CREATE OR REPLACE VIEW fact_team_game_performance AS
SELECT 
	season::int AS season,
    game_id::int AS game_id,
    game_date::int AS game_date,
    player_team AS team_code,
    opposing_team AS opposing_team_code,
    home_or_away,
    situation,
    playoff_game::int AS is_playoff_game,
	x_goals_percentage,
	corsi_percentage,
	fenwick_percentage,
	x_goals_for,
	shots_on_goal_for,
	shot_attempts_for,
	goals_for,
	hits_for,
	takeaways_for,
	shots_on_goal_against,
	shot_attempts_against,
	unblocked_shot_attempts_for,
	unblocked_shot_attempts_against,
	score_adjusted_shots_attempts_for,
	score_adjusted_shots_attempts_against,
	flurry_adjustedx_goals_for,
	flurry_adjustedx_goals_against,
	score_adjusted_unblocked_shot_attempts_for,
	score_adjusted_total_shot_credit_for,
	score_adjusted_unblocked_shot_attempts_against,
	score_adjusted_total_shot_credit_against,
    ice_time,
    x_goals_against,
    goals_against
FROM team_game_stats ;


--3 fact_goalie_game_performance

CREATE OR REPLACE VIEW fact_goalie_game_performance AS
SELECT
    season::int AS season,
    game_id::int AS game_id,
    player_id::int AS goalie_id,
    player_team AS team_code,
    opposing_team AS opposing_team_code,
    game_date::int AS game_date,
    home_or_away,
    situation,
    icetime,
    x_goals,
    goals,
    unblocked_shot_attempts,
    x_rebounds,
    rebounds,
    x_freeze,
    "freeze",
	x_on_goal,
    ongoal AS shots_on_goal,
    x_play_stopped,
    play_stopped,
    x_play_continued_in_zone,
    play_continued_in_zone,
    x_play_continued_outside_zone,
    play_continued_outside_zone,
    flurry_adjusted_x_goals,
    low_danger_shots,
    medium_danger_shots,
    high_danger_shots,
    low_danger_x_goals,
    medium_danger_x_goals,
    high_danger_x_goals,
    low_danger_goals,
    medium_danger_goals,
    high_danger_goals,
    blocked_shot_attempts,
    penalty_minutes,
    penalties
FROM games_goalies_2008_2025;


-- 4. fact_skater_game_performance
 
CREATE OR REPLACE VIEW fact_skater_game_performance AS
SELECT
    season::int AS season,
    game_id::int AS game_id,
    player_id::int AS player_id,
    player_team AS team_code,
    opposing_team AS opposing_team_code,
    home_or_away,
    game_date::int AS game_date,
    position,
    situation,
    icetime,
    shifts,
	game_score,
	ice_time_rank,
	time_on_bench,
    on_ice_x_goals_percentage,
    off_ice_x_goals_percentage,
    on_ice_corsi_percentage,
    off_ice_corsi_percentage,
    on_ice_fenwick_percentage,
    off_ice_fenwick_percentage,
    i_f_x_on_goal,
    i_f_x_goals,
    i_f_primary_assists,
    i_f_secondary_assists,
    i_f_shots_on_goal,
    i_f_missed_shots,
    i_f_blocked_shot_attempts,
    i_f_shot_attempts,
    i_f_points,
    i_f_goals,
    i_f_hits,
    i_f_takeaways,
    i_f_giveaways,
    faceoffs_won,
    faceoffs_lost,
    penalties,
    penalty_minutes,
    penalty_minutes_drawn,
    penalties_drawn,
    shots_blocked_by_player,
    on_ice_f_x_goals,
    on_ice_f_shots_on_goal,
    on_ice_f_shot_attempts,
    on_ice_f_goals,
    on_ice_a_x_goals,
    on_ice_a_shots_on_goal,
    on_ice_a_shot_attempts,
    on_ice_a_goals,
    off_ice_f_x_goals,
    off_ice_a_x_goals,
    off_ice_f_shot_attempts,
    off_ice_a_shot_attempts,
    x_goals_for_after_shifts,
    x_goals_against_after_shifts,
    corsi_for_after_shifts,
    corsi_against_after_shifts,
    fenwick_for_after_shifts,
    fenwick_against_after_shifts
FROM games_skaters_2008_2025;

